name: Test frameworks

on: workflow_dispatch

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build 1 test
        uses: borales/actions-yarn@v4
        with:
          cmd: build 1
      - name: Run test with jest
        uses: borales/actions-yarn@v4
        with:
          cmd: jest
      - name: Run test with vitest
        uses: borales/actions-yarn@v4
        with:
          cmd: vitest
      - name: Build 50 tests
        uses: borales/actions-yarn@v4
        with:
          cmd: build 50
      - name: Run test with jest
        uses: borales/actions-yarn@v4
        with:
          cmd: jest
      - name: Run test with vitest
        uses: borales/actions-yarn@v4
        with:
          cmd: vitest
      - name: Build 100 tests
        uses: borales/actions-yarn@v4
        with:
          cmd: build 100
      - name: Run test with jest
        uses: borales/actions-yarn@v4
        with:
          cmd: jest
      - name: Run test with vitest
        uses: borales/actions-yarn@v4
        with:
          cmd: vitest
      - name: Build 200 tests
        uses: borales/actions-yarn@v4
        with:
          cmd: build 200
      - name: Run test with jest
        uses: borales/actions-yarn@v4
        with:
          cmd: jest
      - name: Run test with vitest
        uses: borales/actions-yarn@v4
        with:
          cmd: vitest
